//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSWcfService.Code.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch_Page
    {
        public System.Guid batch_id { get; set; }
        public System.Guid production_id { get; set; }
        public int page_number { get; set; }
        public System.DateTime last_modified_date { get; set; }
        public string last_modified_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public long occ_version { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Page Page { get; set; }
    }
}
