//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSWcfService.Code.DAL.EF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Production
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Production()
        {
            this.Pages = new HashSet<Page>();
        }
    
        public System.Guid id { get; set; }
        [IgnoreDataMember]
        public Nullable<long> indexing_unit_id { get; set; }
        public string type_code { get; set; }
        public string client_code { get; set; }
        [IgnoreDataMember]
        public System.DateTime last_modified_date { get; set; }
        [IgnoreDataMember]
        public string last_modified_by { get; set; }
        [IgnoreDataMember]
        public System.DateTime created_date { get; set; }
        [IgnoreDataMember]
        public string created_by { get; set; }
        public long occ_version { get; set; }

        [IgnoreDataMember]
        public virtual Client Client { get; set; }
        [IgnoreDataMember]
        public virtual IndexingUnit IndexingUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
        [IgnoreDataMember]
        public virtual ProductionType ProductionType { get; set; }
    }
}
