//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSWcfServices.Code.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocElementHeader
    {
        public System.Guid doc_id { get; set; }
        public short doc_element_id { get; set; }
        public string header_text { get; set; }
    
        public virtual DocElement DocElement { get; set; }
    }
}
