//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMDBService.Code.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigurationAsset()
        {
            this.AccessKeys = new HashSet<AccessKey>();
        }
    
        public string code { get; set; }
        public string group { get; set; }
        public string subgroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessKey> AccessKeys { get; set; }
    }
}
