//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSWcfService.App_Code.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Index
    {
        public long indexing_unit_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public Nullable<byte> order { get; set; }
        public string schema_code { get; set; }
    
        public virtual IndexingUnit IndexingUnit { get; set; }
        public virtual IndexValueDateTime IndexValueDateTime { get; set; }
        public virtual IndexValueText IndexValueText { get; set; }
    }
}
