//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSWcfService.App_Code.DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMSEntities : DbContext
    {
        public DMSEntities()
            : base("name=DMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batch { get; set; }
        public virtual DbSet<Batch_Page> Batch_Page { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DocGroup> DocGroup { get; set; }
        public virtual DbSet<DocGroupType> DocGroupType { get; set; }
        public virtual DbSet<DocType> DocType { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Index> Index { get; set; }
        public virtual DbSet<IndexingUnit> IndexingUnit { get; set; }
        public virtual DbSet<IndexValueDateTime> IndexValueDateTime { get; set; }
        public virtual DbSet<IndexValueText> IndexValueText { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<ProductionType> ProductionType { get; set; }
        public virtual DbSet<Repository> Repository { get; set; }
    }
}
